import { Eyebrow } from "@/components/ui/eyebrow";
import { GoDeeper } from "@/components/ui/go-deeper";
import { PathChip } from "@/components/ui/path-chip";
import { Reveal, Stagger } from "@/components/ui/reveal";
import { Section } from "@/components/ui/section";
import { SplitHeading } from "@/components/ui/split-heading";
import { StatTicker } from "@/components/ui/stat-ticker";
import { security, VERIFIED_AT } from "@/data/system";

/* ----------------------------------------------------------------------------
 * Verbatim figures from the discovery dossier (harness → "Guardian + Sentinel")
 * that don't live in src/data/system.ts.
 * ------------------------------------------------------------------------- */

// source: "240-min sliding TTL, RAM-only tmpfs, 120s phone-approval timeout" — guardian.py config defaults (lines 73–77)
const PHONE_APPROVAL_TIMEOUT_S = 120;
// source: "Rule cache TTL: 60 seconds (cleared instantly when a learned rule lands)" — sentinel-guard.py:21
const RULE_CACHE_TTL_S = 60;
// source: "Active Sentinel rules: 25 (15 rewrite, 10 block, 1 learned)" — sentinel-rules.yaml header, generated 2026-06-12
const RULES_REWRITE = 15;
const RULES_BLOCK = 10;
// source: "sentinel-rules.yaml contains rule 'learned-20260611-030215' of type rewrite_command, generated by the leak detector on 2026-06-11"
const LEARNED_RULE_ID = "learned-20260611-030215";
// source: "Leak events lost before kill-chain fix: 65 (dead-lettered by a guard clause; fixed r2 CS-1)" — post-tool-logger-core.py:598–604
const DEAD_LETTERED_LEAKS = 65;
// source: "Shannon > 3.5 (MCP args) / > 4.5 + 3-of-4 char classes (file writes), min length 12" — sentinel-guard.py:291–393
const ENTROPY_MCP_ARGS = 3.5;
const ENTROPY_FILE_WRITES = 4.5;
const ENTROPY_MIN_LEN = 12;
// source: "/edit-protected write allow-list: 3 path+host entries (strictly smaller than read surface)" — edit-allow-list.yaml
const WRITE_ALLOWLIST_ENTRIES = 3;
// source: "~14 per-service handlers in a 25KB rotation script" — rotate-credential.sh case branches
const ROTATION_SCRIPT_KB = 25;
// source: system.ts security.regressionTests note — "80/80 green across 9 groups"
const REGRESSION_GROUPS = 9;

/* ---- The interception stack, top of funnel to last resort ---------------- */

interface SecurityLayer {
  k: string;
  name: string;
  mechanism: string;
  detail: string;
  receipt: { path: string; note?: string };
}

const LAYERS: SecurityLayer[] = [
  {
    k: "L1",
    name: "Guardian daemon",
    mechanism: "sole holder of plaintext secrets",
    detail: `A ${security.guardianLines.toLocaleString("en-US")}-line Python broker — ${security.guardianEndpoints} endpoints on localhost only, nothing routable. Values are fetched from 1Password into a RAM-only tmpfs session with a ${security.sessionTtlMinutes}-minute sliding TTL; sensitive operations push a phone approval that expires in ${PHONE_APPROVAL_TIMEOUT_S} s. The broker runs as its own Unix user — even full code execution in the model’s session cannot reach the vault token.`,
    receipt: { path: ".credentials/guardian/guardian.py", note: "2,811 lines" },
  },
  {
    k: "L2",
    name: "Sentinel mesh",
    mechanism: `${security.hookEventsInMesh} hook events, one enforcement surface`,
    detail:
      "SessionStart regenerates the rule set from the credential map, PreToolUse guards every call, PostToolUse leak-scans every output, SubagentStart propagates protection into every spawned agent, and Stop turns incidents into rules. Hook events are platform primitives; every line wired into them is Hermes.",
    receipt: { path: ".claude/settings.local.json", note: "5 events wired" },
  },
  {
    k: "L3",
    name: "PreToolUse interception",
    mechanism: "ALLOW · REWRITE · BLOCK — upstream of execution",
    detail: `One ${security.preToolUseGuardLines}-line guard intercepts Bash, Read, Grep, Write, Edit and every MCP tool. Credential-exposing reads are rewritten, not refused: the command is swapped for a redacted Guardian read and the model sees [GUARDIAN:key-name] placeholders. The agent keeps working; the secret never exists in its context.`,
    receipt: { path: ".claude/hooks/sentinel-guard.py", note: "491 lines" },
  },
  {
    k: "L4",
    name: "Entropy detection",
    mechanism: "values caught on the way in",
    detail: `Secrets pasted into writes are caught by shape, not by list: high-entropy tokens adjacent to credential keywords — Shannon entropy above ${ENTROPY_MCP_ARGS} in MCP arguments, above ${ENTROPY_FILE_WRITES} with a 3-of-4 character-class mix in file writes, minimum length ${ENTROPY_MIN_LEN} — with safe-pattern exemptions tuned against code and regex false positives.`,
    receipt: { path: "sentinel-guard.py:291–393" },
  },
  {
    k: "L5",
    name: "Learned rules",
    mechanism: "the firewall writes itself",
    detail: `When a leak is detected in tool output, the Stop hook authors a new rewrite rule on its own, clears the ${RULE_CACHE_TTL_S}-second rule cache so it binds on the very next tool call, and files the incident to memory. Learned rules persist ${security.learnedRuleRetentionDays} days. The same leak path cannot succeed twice.`,
    receipt: { path: ".credentials/sentinel-rules.yaml", note: "25 rules" },
  },
];

/* ---- Learned-rule lifecycle (the L5 loop, step by step) ------------------- */

const LIFECYCLE: ReadonlyArray<{ k: string; label: string; detail: string }> = [
  {
    k: "01",
    label: "leak detected",
    detail: "PostToolUse scans tool output against Guardian’s in-memory value cache",
  },
  {
    k: "02",
    label: "rule auto-authored",
    detail: "the Stop hook appends a rewrite rule — no human in the loop",
  },
  {
    k: "03",
    label: "cache cleared",
    detail: `the ${RULE_CACHE_TTL_S} s rule cache is dropped instantly; the rule binds immediately`,
  },
  {
    k: "04",
    label: `retained ${security.learnedRuleRetentionDays} days`,
    detail: `the generator preserves learned rules across regenerations, pruning at ${security.learnedRuleRetentionDays} days`,
  },
];

/* ---- Instrument row ------------------------------------------------------- */

const INSTRUMENTS: ReadonlyArray<{
  value: number;
  suffix: string;
  label: string;
  receipt: { path: string; note?: string };
}> = [
  {
    value: security.credentials,
    suffix: "",
    label: "credentials brokered",
    receipt: { path: ".credentials/credential-map.yaml", note: "values only in 1Password" },
  },
  {
    value: security.sentinelRules,
    suffix: "",
    label: "active Sentinel rules",
    receipt: { path: ".credentials/sentinel-rules.yaml", note: "1 machine-learned" },
  },
  {
    value: security.guardianEndpoints,
    suffix: "",
    label: "localhost-only endpoints",
    receipt: { path: "guardian.py:2054–2094" },
  },
  {
    value: security.regressionTests,
    suffix: "/80",
    label: "security regressions green",
    receipt: { path: ".claude/tests/", note: `${REGRESSION_GROUPS} groups` },
  },
];

/**
 * DeepSecurity — Guardian/Sentinel as a layered diagram-table: the five
 * interception layers, the learned-rule lifecycle with the real one-rule
 * story, an instrument row of verified figures, and GoDeeper receipts for
 * the kill-chain revival, the write-protection workflow, and rotation.
 */
export function DeepSecurity() {
  return (
    <Section id="security" max="6xl">
      {/* Header */}
      <Reveal className="max-w-3xl">
        <Eyebrow>Guardian + Sentinel</Eyebrow>
        <SplitHeading as="h2" className="text-h1 mt-4 text-white">
          Structural security.
        </SplitHeading>
        <p className="text-body-lg mt-5 text-pretty text-text-secondary">
          The model can use {security.credentials} credentials and can read none of them. Guardian
          holds the secrets; Sentinel rewrites the model’s own tool calls before they execute.
          Enforcement is deterministic code outside the model — a wall it can’t see over, not a
          rule it’s asked to remember.
        </p>
      </Reveal>

      {/* Interception stack — layered diagram-table */}
      <Stagger as="ul" className="relative mt-14 border-t border-hairline" gap={0.09}>
        {/* connector spine */}
        <span
          aria-hidden="true"
          className="absolute top-3 bottom-3 left-[19px] hidden w-px bg-hairline sm:block"
        />
        {LAYERS.map((layer) => (
          <Reveal asChild as="li" key={layer.k} className="relative">
            <div className="grid gap-3 border-b border-hairline py-6 sm:grid-cols-[40px_220px_1fr] sm:gap-6">
              {/* node */}
              <div className="flex items-start gap-3 sm:block">
                <span className="relative z-10 inline-flex h-10 w-10 items-center justify-center rounded-lg border border-hairline bg-surface-1 font-mono text-[11px] text-brand-300">
                  {layer.k}
                </span>
              </div>
              <div>
                <h3 className="text-h3 text-white">{layer.name}</h3>
                <p className="mt-1 font-mono text-[11px] tracking-[0.08em] text-brand-300/90 uppercase">
                  {layer.mechanism}
                </p>
              </div>
              <div>
                <p className="text-sm leading-relaxed text-ink-muted">{layer.detail}</p>
                <div className="mt-3">
                  <PathChip path={layer.receipt.path} note={layer.receipt.note} />
                </div>
              </div>
            </div>
          </Reveal>
        ))}
      </Stagger>

      {/* Learned-rule lifecycle + the real story */}
      <Reveal className="mt-14">
        <div className="glass rounded-2xl p-6 sm:p-8">
          <p className="font-mono text-[11px] tracking-[0.14em] text-ink-subtle uppercase">
            The learned-rule lifecycle
          </p>
          <div className="mt-5 grid divide-y divide-hairline sm:grid-cols-4 sm:divide-x sm:divide-y-0">
            {LIFECYCLE.map((step) => (
              <div key={step.k} className="py-4 sm:px-5 sm:py-0 sm:first:pl-0 sm:last:pr-0">
                <p className="font-mono text-[11px] text-ink-faint">{step.k}</p>
                <p className="mt-1 font-mono text-[13px] text-ink">{step.label}</p>
                <p className="mt-1.5 text-[13px] leading-relaxed text-ink-subtle">{step.detail}</p>
              </div>
            ))}
          </div>
          <p className="mt-7 border-t border-hairline pt-6 text-sm leading-relaxed text-ink-muted">
            {security.sentinelRules} active rules guard {security.credentials} credentials —{" "}
            {RULES_REWRITE} rewrite, {RULES_BLOCK} block. Twenty-four were generated from the
            credential map. Exactly {security.learnedRules} —{" "}
            <span className="font-mono text-[13px] text-brand-300">{LEARNED_RULE_ID}</span> — the
            system wrote itself, the night it caught a dashboard password bleeding into tool
            output.
          </p>
        </div>
      </Reveal>

      {/* Instrument row */}
      <Stagger className="mt-12 grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4" gap={0.07}>
        {INSTRUMENTS.map((stat) => (
          <Reveal asChild key={stat.label}>
            <div>
              <p className="font-mono text-4xl font-medium text-white">
                <StatTicker value={stat.value} suffix={stat.suffix} />
              </p>
              <p className="mt-2 text-[13px] text-ink-subtle">{stat.label}</p>
              <div className="mt-3">
                <PathChip path={stat.receipt.path} note={stat.receipt.note} />
              </div>
            </div>
          </Reveal>
        ))}
      </Stagger>
      <Reveal className="mt-6">
        <p className="font-mono text-[11px] text-ink-faint">verified {VERIFIED_AT}</p>
      </Reveal>

      {/* Expert detail */}
      <div className="mt-14 space-y-6">
        <GoDeeper summary={`the kill-chain revival — ${DEAD_LETTERED_LEAKS} dead-lettered leak events`}>
          <p>
            The self-sealing loop shipped broken, and the system’s own audit caught it. A generic
            guard clause dead-lettered name-less leak signals before the rule-writer ever saw them:{" "}
            {DEAD_LETTERED_LEAKS} real leak events were silently lost, and the celebrated
            kill-chain had never once fired. Round-2 change-set CS-1 bypassed the generic guards
            for security signal types — and the post-mortem is written into the code as a comment
            at the signal-emission site. The proof of the fix is the rule above: on 2026-06-11 the
            revived chain fired live, end to end, without being asked.
          </p>
          <div className="mt-3">
            <PathChip path="post-tool-logger-core.py:598–604" note="inline post-mortem" />
          </div>
        </GoDeeper>

        <GoDeeper summary="the write-protected file workflow">
          <p>
            Mutating a credential-bearing file from Bash is structurally blocked: a
            WRITE_INDICATORS regex catches <code className="font-mono">sed -i</code>,{" "}
            <code className="font-mono">tee</code>, shell redirection, cp/mv/install/truncate,{" "}
            <code className="font-mono">dd of=</code>, even Python opened for write. The block
            message teaches the safe alternative inline — a two-step Guardian /edit-protected call
            in which the protected path never appears in command text. The write allow-list holds
            just {WRITE_ALLOWLIST_ENTRIES} path+host entries, deliberately smaller than the read
            surface, and it forbids the model from editing sentinel-rules.yaml and
            credential-map.yaml outright: the LLM must not mutate its own guardrails.
          </p>
          <div className="mt-3 flex flex-wrap gap-2">
            <PathChip path="sentinel-guard.py:198–232" note="WRITE_INDICATORS" />
            <PathChip path=".credentials/edit-allow-list.yaml" note="3 entries" />
          </div>
        </GoDeeper>

        <GoDeeper summary={`rotation without exposure — ~${security.rotationHandlers} per-service handlers`}>
          <p>
            Rotation is orchestrated by the agent and executed by handlers it can’t see into: a{" "}
            {ROTATION_SCRIPT_KB} KB rotation script with ~{security.rotationHandlers} per-service
            handlers — SSH, four WiFi VLANs, UniFi, Uptime Kuma, SABnzbd, Sonarr, Radarr, Prowlarr,
            Tdarr, two Wazuh tiers — plus provisioning that generates passwords inside Guardian
            with per-credential phone approval. Create, apply, rotate: the value never enters the
            model’s context at any step.
          </p>
          <div className="mt-3">
            <PathChip path=".credentials/rotate-credential.sh" note="~14 handlers" />
          </div>
        </GoDeeper>
      </div>
    </Section>
  );
}
