import { KeyRound, ShieldCheck, Terminal } from "lucide-react";
import { security, VERIFIED_AT } from "@/data/system";
import { Eyebrow } from "@/components/ui/eyebrow";
import { GlassCard } from "@/components/ui/glass-card";
import { GoDeeper } from "@/components/ui/go-deeper";
import { JargonChip } from "@/components/ui/jargon";
import { PathChip } from "@/components/ui/path-chip";
import { Reveal, Stagger, StaggerItem } from "@/components/ui/reveal";
import { Section } from "@/components/ui/section";
import { SplitHeading } from "@/components/ui/split-heading";
import { StatTicker } from "@/components/ui/stat-ticker";

/* ----------------------------------------------------------------------------
   Dossier facts (everything else renders from src/data/system.ts → security)
   -------------------------------------------------------------------------- */
// source: /tmp/dabarkle-discovery.json → harness[2].facts — "sentinel-rules.yaml
// contains rule 'learned-20260611-030215' of type rewrite_command, generated by
// the leak detector on 2026-06-11"
const LEARNED_RULE_ID = "learned-20260611-030215";
const LEARNED_RULE_DATE = "2026-06-11";
// source: /tmp/dabarkle-discovery.json → harness[2].facts — PreToolUse matcher
// "Bash|Read|Grep|Write|Edit|mcp__.*" deciding ALLOW / REWRITE / BLOCK
const INTERCEPT_MATCHER = "Bash|Read|Grep|Write|Edit|mcp__.*";
// source: /tmp/dabarkle-discovery.json → harness[2].diagram_idea — the canonical
// rewrite example: `cat docker-compose.yml` → `curl guardian/read-redacted`,
// placeholder [GUARDIAN:sonarr-api-key]
const EXAMPLE_PROPOSED = "cat docker-compose.yml";
const EXAMPLE_REWRITTEN = "curl guardian/read-redacted";
const EXAMPLE_PLACEHOLDER = "[GUARDIAN:sonarr-api-key]";
// source: /tmp/dabarkle-discovery.json → harness[2].facts — entropy thresholds:
// Shannon > 3.5 (MCP args), > 4.5 + 3-of-4 character classes (file writes),
// minimum token length 12
const ENTROPY_MCP = 3.5;
const ENTROPY_WRITE = 4.5;
const ENTROPY_MIN_LENGTH = 12;

const fmt = (n: number) => n.toLocaleString("en-US");

/** The four trust numbers under the kill-chain story. All from system.ts. */
const STATS: ReadonlyArray<{ value: number; suffix?: string; label: string }> = [
  { value: security.credentials, label: "credentials brokered — usable, never readable" },
  { value: security.sentinelRules, label: "active rules — one written by the system itself" },
  {
    value: security.regressionTests,
    suffix: `/${security.regressionTests}`,
    label: "security regression tests green",
  },
  {
    value: security.sessionTtlMinutes,
    suffix: " min",
    label: "sliding session TTL — RAM-only, phone-approved",
  },
];

/* ----------------------------------------------------------------------------
   Local pieces
   -------------------------------------------------------------------------- */

/** Arrow between schematic steps: vertical tick on mobile, dashed arrow on md+. */
function FlowConnector() {
  return (
    <div aria-hidden="true" className="flex items-center justify-center">
      <span className="block h-7 w-px bg-gradient-to-b from-[var(--color-hairline-strong)] to-transparent md:hidden" />
      <svg
        width="32"
        height="12"
        viewBox="0 0 32 12"
        fill="none"
        className="hidden text-ink-faint md:block"
      >
        <line x1="1" y1="6" x2="24" y2="6" stroke="currentColor" strokeDasharray="3 3" />
        <path
          d="M24 1.5 30.5 6 24 10.5"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </div>
  );
}

/** One step of the rewrite schematic: numbered card with a mono trace block. */
function FlowStep({
  k,
  title,
  icon,
  trace,
  children,
}: {
  k: string;
  title: string;
  icon: React.ReactNode;
  trace: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <GlassCard tone="subtle" className="flex h-full flex-col gap-3 p-5">
      <div className="flex items-center justify-between">
        <span className="font-mono text-[11px] tracking-[0.14em] text-ink-faint">{k}</span>
        {icon}
      </div>
      <h3 className="text-sm font-semibold text-ink">{title}</h3>
      <div className="rounded-lg border border-hairline bg-canvas/70 px-3 py-2 font-mono text-[12px] leading-relaxed">
        {trace}
      </div>
      <p className="text-[13px] leading-relaxed text-ink-subtle">{children}</p>
    </GlassCard>
  );
}

/* ----------------------------------------------------------------------------
   Section
   -------------------------------------------------------------------------- */

/**
 * Guardrails — "Credentials the model can't reach." The structural-security
 * argument in three moves: a 3-step PreToolUse rewrite schematic, the
 * kill-chain story (the one rule the system wrote for itself), and the trust
 * stat row. Server component; all motion lives in imported primitives.
 */
export function Guardrails() {
  return (
    <Section id="guardrails" max="6xl">
      {/* Header */}
      <div className="mb-12 max-w-3xl sm:mb-14">
        <Reveal>
          <Eyebrow>Guardian + Sentinel — structural security</Eyebrow>
        </Reveal>
        <SplitHeading as="h2" className="text-h1 mt-4 text-balance text-white">
          Credentials the model can’t reach.
        </SplitHeading>
        <Reveal delay={0.15}>
          <p className="text-body-lg mt-5 text-pretty text-ink-muted">
            Hermes never asks the model to keep a secret. Sentinel sits between every proposed
            tool call and its execution: anything credential-shaped is{" "}
            <JargonChip term="PreToolUse rewriting">rewritten in flight</JargonChip>, while the
            real values stay inside a 1Password-brokered daemon the model can call but never
            read — all {security.credentials} of them.
          </p>
        </Reveal>
      </div>

      {/* 3-step rewrite schematic */}
      <Stagger className="grid grid-cols-1 gap-2 md:grid-cols-[1fr_2.5rem_1fr_2.5rem_1fr] md:items-stretch md:gap-0">
        <StaggerItem className="md:h-full">
          <FlowStep
            k="01"
            title="The model proposes"
            icon={<Terminal aria-hidden="true" className="h-4 w-4 text-brand-400" />}
            trace={
              <>
                <p className="text-ink-muted">
                  <span aria-hidden="true" className="mr-1.5 select-none text-brand-400">
                    ❯
                  </span>
                  {EXAMPLE_PROPOSED}
                </p>
                <p className="text-ink-faint">
                  # would print SONARR_API_KEY=
                  <span aria-hidden="true">••••••••••••</span>
                  <span className="sr-only">(redacted)</span>
                </p>
              </>
            }
          >
            An ordinary read — except this compose file carries live service keys. Unrewritten,
            the secret lands in the transcript and in every log downstream.
          </FlowStep>
        </StaggerItem>

        <StaggerItem direction="none">
          <FlowConnector />
        </StaggerItem>

        <StaggerItem className="md:h-full">
          <FlowStep
            k="02"
            title="Sentinel rewrites"
            icon={<ShieldCheck aria-hidden="true" className="h-4 w-4 text-brand-400" />}
            trace={
              <>
                <p className="text-ink-faint line-through decoration-error/40">
                  {EXAMPLE_PROPOSED}
                </p>
                <p className="text-brand-300">{EXAMPLE_REWRITTEN}</p>
              </>
            }
          >
            The {security.preToolUseGuardLines}-line PreToolUse guard swaps the command before it
            runs. What reaches context:{" "}
            <code className="rounded border border-hairline bg-white/[0.04] px-1 py-0.5 font-mono text-[11px] text-accent-300">
              {EXAMPLE_PLACEHOLDER}
            </code>{" "}
            — the shape of the file, none of the value.
          </FlowStep>
        </StaggerItem>

        <StaggerItem direction="none">
          <FlowConnector />
        </StaggerItem>

        <StaggerItem className="md:h-full">
          <FlowStep
            k="03"
            title="Guardian executes"
            icon={<KeyRound aria-hidden="true" className="h-4 w-4 text-brand-400" />}
            trace={
              <>
                <p className="text-ink-muted">
                  <span aria-hidden="true" className="mr-1.5 select-none text-brand-400">
                    ❯
                  </span>
                  guardian /execute
                </p>
                <p className="text-ink-faint"># value injected in-process, at runtime</p>
              </>
            }
          >
            When a job genuinely needs the secret, Guardian injects it inside its own process —
            fetched from a phone-approved, RAM-only session. The value exists at execution time,
            never in the model’s context.
          </FlowStep>
        </StaggerItem>
      </Stagger>

      <Reveal delay={0.1}>
        <p className="mt-8 text-center text-[15px] text-ink-subtle">
          Not a rule it follows — a wall it can’t see over.{" "}
          <span className="font-medium text-ink">Structural, not behavioral.</span>
        </p>
      </Reveal>

      <div className="mt-8">
        <GoDeeper summary="what the guard intercepts, and how values are caught inbound">
          <div className="space-y-3">
            <p>
              A single PreToolUse hook screens every command, file read, and MCP call —
              matcher{" "}
              <code className="rounded bg-white/[0.04] px-1 py-0.5 font-mono text-[12px] text-ink-muted">
                {INTERCEPT_MATCHER}
              </code>{" "}
              — with a three-way verdict: allow, rewrite, or block.
            </p>
            <p>
              {/* source: dossier harness[2].facts — inbound value detection + HIGH-priority phone notification on block */}
              Values are stopped inbound too: Edit, Write, and MCP arguments are scanned for
              high-entropy tokens adjacent to credential keywords — Shannon entropy above{" "}
              {ENTROPY_MCP} for MCP arguments, above {ENTROPY_WRITE} with a 3-of-4
              character-class mix and minimum length {ENTROPY_MIN_LENGTH} for file writes. A
              block fires a high-priority phone notification.
            </p>
            <p>
              {/* source: dossier harness[2].facts — /edit-protected allow-list forbids editing
                  sentinel-rules.yaml and credential-map.yaml ("the LLM must not mutate its own guardrails") */}
              And the write surface is deliberately smaller than the read surface: the allow-list
              structurally forbids the model from editing sentinel-rules.yaml or
              credential-map.yaml. It cannot mutate its own guardrails.
            </p>
          </div>
        </GoDeeper>
      </div>

      {/* Kill-chain story — the rule the system wrote for itself */}
      {/* source: dossier harness[2].facts — closed leak kill-chain: PostToolUse /scan-for-leaks
          hit → signal + alert entry → Stop hook appends learned rewrite rule, clears the rule
          cache, writes an ambient incident record; learned rules kept with 90-day pruning */}
      <Reveal className="mt-14">
        <GlassCard gradientBorder className="p-7 sm:p-9">
          <div className="flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between">
            <div className="max-w-2xl">
              <p className="font-mono text-overline text-brand-300">
                the kill-chain — a loop that closed itself
              </p>
              <h3 className="text-h2 mt-3 text-balance text-white">
                One of the {security.sentinelRules} active rules wasn’t written by a human.
              </h3>
              <p className="mt-4 text-[15px] leading-relaxed text-ink-muted">
                On {LEARNED_RULE_DATE}, the PostToolUse leak scanner caught a dashboard password
                surfacing in tool output. The detection raised a signal; at turn end, the Stop
                hook appended a learned rewrite rule to the rulebook, cleared the live rule
                cache, and filed the incident to ambient memory. The path that leaked is now
                structurally sealed.
              </p>
              <p className="mt-3 text-[15px] leading-relaxed text-ink-muted">
                Detection to permanent fix, no human in the loop. Machine-written rules survive
                every rulebook regeneration and carry a {security.learnedRuleRetentionDays}-day
                retention window — trust, but expire.
              </p>
            </div>
            {/* The artifact itself, as it appears in sentinel-rules.yaml */}
            <div className="shrink-0 rounded-xl border border-hairline bg-canvas/70 p-4 font-mono text-[12px] leading-relaxed lg:w-80">
              <p className="text-ink-faint"># written by the Stop hook, not a human</p>
              <p className="mt-1 text-ink-muted">
                - id: <span className="text-accent-300">{LEARNED_RULE_ID}</span>
              </p>
              <p className="pl-4 text-ink-muted">type: rewrite_command</p>
              <p className="pl-4 text-ink-muted">origin: leak detector · {LEARNED_RULE_DATE}</p>
            </div>
          </div>
        </GlassCard>
      </Reveal>

      {/* Trust numbers */}
      <Stagger className="mt-14 grid grid-cols-2 gap-x-6 gap-y-10 lg:grid-cols-4">
        {STATS.map((s) => (
          <StaggerItem key={s.label} className="border-l border-hairline pl-5">
            <StatTicker
              value={s.value}
              suffix={s.suffix}
              className="font-mono text-3xl font-medium text-ink sm:text-4xl"
            />
            <p className="mt-2 max-w-[16rem] text-[13px] leading-snug text-ink-subtle">
              {s.label}
            </p>
          </StaggerItem>
        ))}
      </Stagger>

      {/* Receipts */}
      <Reveal className="mt-10 flex flex-wrap items-center gap-2">
        <PathChip
          path=".claude/hooks/sentinel-guard.py"
          note={`${security.preToolUseGuardLines} lines`}
        />
        <PathChip
          path=".credentials/guardian/guardian.py"
          note={`${fmt(security.guardianLines)} lines`}
        />
        <span className="font-mono text-[11px] text-ink-faint">verified {VERIFIED_AT}</span>
      </Reveal>
    </Section>
  );
}
